name: flutter_bbcode
description: A package to display BBCode text in Flutter apps. Manage your own tags or use those of others.
version: 1.0.0
repository: https://github.com/MartenM/flutter_bbcode
issue_tracker: https://github.com/MartenM/flutter_bbcode/issues


environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Parser for BBCode - Updated for NULL-Safety
  bbob_dart: ^0.2.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0